export const IPC_CHANNELS = {
  ACCOUNT: {
    CREATE: 'account:create',
    GET_ALL: 'account:get-all',
    DELETE: 'account:delete',
    CONNECT: 'account:connect',
    DISCONNECT: 'account:disconnect',
    STATUS_CHANGED: 'account:status-changed',
    QR_RECEIVED: 'account:qr-received',
    PAIRING_CODE_RECEIVED: 'account:pairing-code-received',
  },
  MESSAGE: {
    CREATE_TEMPLATE: 'message:create-template',
    GET_ALL_TEMPLATES: 'message:get-all-templates',
    UPDATE_TEMPLATE: 'message:update-template',
    DELETE_TEMPLATE: 'message:delete-template',
    SEND_BULK: 'message:send-bulk',
    STOP_SENDING: 'message:stop-sending',
    SENDING_PROGRESS: 'message:sending-progress',
    SENDING_COMPLETE: 'message:sending-complete',
    SELECT_IMAGE: 'message:select-image',
  },
  CONTACT: {
    FETCH_GROUPS: 'contact:fetch-groups',
    FETCH_PERSONAL_CHATS: 'contact:fetch-personal-chats',
    EXTRACT_FROM_GROUPS: 'contact:extract-from-groups',
    EXTRACT_FROM_CHATS: 'contact:extract-from-chats',
    EXPORT_TO_EXCEL: 'contact:export-to-excel',
    SAVE_CONTACTS: 'contact:save-contacts',
    GET_SAVED_CONTACTS: 'contact:get-saved-contacts',
  },
  SCHEDULER: {
    CREATE_JOB: 'scheduler:create-job',
    GET_ALL_JOBS: 'scheduler:get-all-jobs',
    CANCEL_JOB: 'scheduler:cancel-job',
    DELETE_JOB: 'scheduler:delete-job',
    JOB_PROGRESS: 'scheduler:job-progress',
  },
  LICENSE: {
    VALIDATE: 'license:validate',
    ACTIVATE: 'license:activate',
    GET_STATE: 'license:get-state',
    GET_FINGERPRINT: 'license:get-fingerprint',
    OPEN_LICENSE_PAGE: 'license:open-license-page',
  },
  CUSTOMER: {
    CREATE: 'customer:create',
    GET_ALL: 'customer:get-all',
    GET_BY_ID: 'customer:get-by-id',
    UPDATE: 'customer:update',
    DELETE: 'customer:delete',
    SEARCH: 'customer:search',
    GET_STATS: 'customer:get-stats',
    EXPORT: 'customer:export',
  },
  PRODUCT: {
    CREATE: 'product:create',
    GET_ALL: 'product:get-all',
    UPDATE: 'product:update',
    DELETE: 'product:delete',
  },
  PAYMENT: {
    CREATE: 'payment:create',
    GET_ALL: 'payment:get-all',
    GET_BY_CUSTOMER: 'payment:get-by-customer',
    UPDATE: 'payment:update',
    DELETE: 'payment:delete',
    EXPORT: 'payment:export',
  },
} as const;

export type IPCChannels = typeof IPC_CHANNELS;
